
# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.6

        - os: osx
          language: generic


script:

    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install --upgrade pip;
            python -m pip install coverage;
            python -m pip install -U coverage;
            pip install coverage;
            pip install -U coverage;
            pip install codecov;
            pip install codacy-coverage;
            pip install python-coveralls;
            pip install -r requirements.txt;
            python --version;
            ls;
            pwd;
            coverage help;
            coverage --version;
            coverage run source/unit_tests.py;
            codecov;
            coveralls;
            python-codacy-coverage -r coverage.xml;
      fi

    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew upgrade python;
            pip3 install --user -r requirements.txt;
            python3 source/unit_tests.py;
      fi


notifications:
    email: false

