Trabalho 2 Formais: Production Class Reference
Production Class Reference
Public Member Functions
def __init__ (self, symbols=[], lock=False)
def __setattr__ (self, name, value)
def __repr__ (self)
def __str__ (self)
def __lt__ (self, other)
def __getitem__ (self, key)
def __setitem__ (self, key, element)
def __iter__ (self)
def __next__ (self)
def combinations (self, non_terminal_epsilon=[])
def filter_non_terminals (self, non_terminal_epsilon, non_terminals_to_keep)
def remove_everything_after (self, index)
def remove_everything_before (self, index)
def remove (self, index)
def remove_terminal (self, index)
def remove_non_terminal (self, index)
def replace (self, target_index, new_production)
def trim_epsilons (self, new_copy=False)
def peek_next (self, lookahead=1)
def following_symbols (self)
def add (self, symbol)
def lock (self)
def check_consistency (self)
def terminals (self, index=-1)
def non_terminals (self, index=-1, position=False)
def is_last (self, symbol)
Public Member Functions inherited from LockableType
def __init__ (self)
def __setattr__ (self, name, value)
def __eq__ (self, other)
def __hash__ (self)
def __repr__ (self)
def __str__ (self)
def __len__ (self)
def lock (self)
def new (self, unlocked=True)
Static Public Member Functions
def copy_productions_except_epsilon (source, destine)
Public Attributes
symbols
A list of Terminal's and NonTerminal's this production is composed.
sequence
The last symbols' sequence starting from 1.
len
Caches the length of this symbol, useful after its changes have been locked by lock()
Public Attributes inherited from LockableType
locked
Controls whether the attributes changes of this object are allow or not.
str
Caches the string representation of this object, after locking its attributes changes with lock()
len
The cached length of this object, used while this object is in locked state.
Detailed Description
    A full featured Chomsky Grammar production.
Constructor & Destructor Documentation
__init__()
def __init__ (self, symbols = [], lock = False)
    Creates a new fresh production.
    `symbols` a list of initial symbols to add to the production
    `lock` if True, the object will be immediately locked upon creation
Member Function Documentation
__getitem__()
def __getitem__ (self, key)
    Called by Python automatically when indexing a production as in object[index].
__iter__()
def __iter__ (self)
    Called by Python automatically when iterating over this set and python wants to start
    the iteration process.
    `self._index` internally controls the which one is the current item in an iteration over
    an production
__lt__()
def __lt__ (self, other)
    Operator less than `<` used when comparing production's objects.
    A symbol is compared explicitly by its string representation.
__next__()
def __next__ (self)
    Return the next item immediate for the current iteration.
__repr__()
def __repr__ (self)
    Return a more complete and precise string representation of this object, useful for
    debugging purposes. But requires the `_USE_STRING` constant to be set to False.
__setattr__()
def __setattr__ (self, name, value)
    Block attributes from being changed after it is activated.
    https://stackoverflow.com/questions/17020115/how-to-use-setattr-correctly-avoiding-infinite-recursion
__setitem__()
def __setitem__ (self, key, element)
    Called by Python automatically when indexing a production as in object[index].
__str__()
def __str__ (self)
    Return a nice string representation of this set.
add()
def add (self, symbol)
    Add a new symbol to the production. If the last added symbol and the current are
    Terminal ones, the old terminal is going to be removed and merged into the new one.
Referenced by Production.filter_non_terminals(), Production.replace(), and Production.trim_epsilons().
check_consistency()
def check_consistency (self)
    Assures the symbol has meaning, i.e., is not empty.
Referenced by ChomskyGrammarSymbol.lock(), and Production.lock().
combinations()
def combinations (self, non_terminal_epsilon = [])
    Return a new set within all its non terminal's removal combinations, accordingly with
    the non terminal's set on `non_terminal_epsilon`.
    How do use itertools in Python to build permutation or combination
    http://thomas-cokelaer.info/blog/2012/11/how-do-use-itertools-in-python-to-build-permutation-or-combination/
copy_productions_except_epsilon()
def copy_productions_except_epsilon (source, destine) static
    Copy all productions from one productions set to another, except the `epsilon_production`.
    Return `True` when the item was added in the destine, `False` when is already exists on destine.
filter_non_terminals()
def filter_non_terminals (self, non_terminal_epsilon, non_terminals_to_keep)
    Removes all non terminal's in the list `non_terminal_epsilon`, except the ones inside
    the list `non_terminals_to_keep`.
following_symbols()
def following_symbols (self)
    Similar to `peek_next()` but get all the following symbols until the end of the
    production. Return an empty list when there are not remaining symbols.
is_last()
def is_last (self, symbol)
    Checks whether the a given symbol is the last in a production.
    `production` is a list of Terminal's and NonTerminal's, and `symbol` is a NonTerminal.
    The last `production` element has its sequence number equal to the production's list
    size.
lock()
def lock (self)
    Call `trim_epsilons()`, `check_consistency()` and its super class `lock()` to block
    further changes to this object attributes.
non_terminals()
def non_terminals (self, index = -1, position = False)
    Get all NonTerminal's this symbol is composed by, on their respective sequence/ordering.
    If `index` is provided greater than `-1`, instead of returning a list, return the list
    nth element. If the `index` is out of range, then an empty set will be returned.
    If `position`, list with tuples with (symbol, position) in the production.
Referenced by Production.combinations().
peek_next()
def peek_next (self, lookahead = 1)
    Inside a item iteration, allow to look the next nth element given by `lookahead`. If the
    search goes past end or it is the last item, return None.
remove()
def remove (self, index)
    Given an index starting from 0, removes the nth symbol's, either Terminal or NonTerminal.
remove_everything_after()
def remove_everything_after (self, index)
    Given an index starting from 0 nth, removes all the symbols after it, excluding the 0 nth symbol.
remove_everything_before()
def remove_everything_before (self, index)
    Given an index starting from 0 nth, removes all the symbols before it excluding 0 nth symbol.
Referenced by Production.following_symbols().
remove_non_terminal()
def remove_non_terminal (self, index)
    Given an index starting from 0, removes the nth non terminal's.
remove_terminal()
def remove_terminal (self, index)
    Given an index starting from 0, removes the nth terminal's.
replace()
def replace (self, target_index, new_production)
    Given an `target_index` starting from 0, replace the nth symbol with the given
    `new_production` symbols.
terminals()
def terminals (self, index = -1)
    Get all Terminal's this symbol is composed by, on their respective sequence/ordering.
    If `index` is provided greater than `-1`, instead of returning a list, return the list
    nth element. If the `index` is out of range, then an empty set will be returned.
trim_epsilons()
def trim_epsilons (self, new_copy = False)
    Removes all meaningless epsilon's, i.e., with no meaning, useless.
    If `new_copy` is True, then instead of modifying the current object, return a new copy
    with epsilon's trimmed.
Referenced by Production.filter_non_terminals(), ChomskyGrammarSymbol.lock(), Production.lock(), Production.remove_everything_after(), Production.remove_everything_before(), and Production.replace().
The documentation for this class was generated from the following file:
production.py