Chomsky Grammar Tools for Context Free Grammars (CFG): ChomskyGrammarTreeTransformer Class Reference
ChomskyGrammarTreeTransformer Class Reference
Public Member Functions
def non_terminal_start (self, non_terminal)
def terminal (self, _terminals)
def non_terminal (self, _non_terminals)
def epsilon (self, _terminal)
def quote (self, _terminal)
def minus (self, _terminal)
def plus (self, _terminal)
def star (self, _terminal)
def comma (self, _terminal)
def colon (self, _terminal)
def dot (self, _terminal)
def double_quote (self, _terminal)
def percentage (self, _terminal)
def dollar (self, _terminal)
def at_sign (self, _terminal)
def sharp (self, _terminal)
def exclamation (self, _terminal)
def backtick (self, _terminal)
def tick (self, _terminal)
def caret (self, _terminal)
def tilde (self, _terminal)
def question (self, _terminal)
def equals (self, _terminal)
def semicolon (self, _terminal)
def slash (self, _terminal)
def backslash (self, _terminal)
def open_paren (self, _terminal)
def close_paren (self, _terminal)
def open_bracket (self, _terminal)
def close_bracket (self, _terminal)
def open_brace (self, _terminal)
def close_brace (self, _terminal)
def production (self, productions)
Detailed Description
    Transforms the AST (Abstract Syntax Tree) nodes into meaningful string representations,
    allowing simple recursive parsing parsing of the AST tree.
    Tree(
            productions,
            [
               Tree( non_terminal, [Token( UCASE_LETTER, 'S' )] ),
               Tree(
                       non_terminals,
                       [
                           Tree( production, [Tree( terminal, [Token( LCASE_LETTER, 'a' )] ), Tree( non_terminal, [Token( UCASE_LETTER, 'A' )] )] ),
                           Tree( production, [Tree( terminal, [Token( LCASE_LETTER, 'a' )] )] )
                       ]
                    )
            ]
        )
Definition at line 50 of file tree_transformer.py.
Member Function Documentation
at_sign()
def at_sign (self, _terminal)
    Converts the tree leaf '@' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 157 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def at_sign(self, _terminal):
         """
             Converts the tree leaf '@' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "@" )
backslash()
def backslash (self, _terminal)
    Converts the tree leaf '\' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 223 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def backslash(self, _terminal):
         """
             Converts the tree leaf '\' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "\\" )
backtick()
def backtick (self, _terminal)
    Converts the tree leaf '`' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 175 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def backtick(self, _terminal):
         """
             Converts the tree leaf '`' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "`" )
caret()
def caret (self, _terminal)
    Converts the tree leaf '^' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 187 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def caret(self, _terminal):
         """
             Converts the tree leaf '^' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "^" )
close_brace()
def close_brace (self, _terminal)
    Converts the tree leaf '}' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 261 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def close_brace(self, _terminal):
         """
             Converts the tree leaf '}' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "}" )
close_bracket()
def close_bracket (self, _terminal)
    Converts the tree leaf ']' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 248 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def close_bracket(self, _terminal):
         """
             Converts the tree leaf ']' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "]" )
close_paren()
def close_paren (self, _terminal)
    Converts the tree leaf ')' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 235 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def close_paren(self, _terminal):
         """
             Converts the tree leaf ')' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, ")" )
colon()
def colon (self, _terminal)
    Converts the tree leaf ':' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 127 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def colon(self, _terminal):
         """
             Converts the tree leaf ':' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, ":" )
comma()
def comma (self, _terminal)
    Converts the tree leaf ',' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 121 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def comma(self, _terminal):
         """
             Converts the tree leaf ',' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "," )
dollar()
def dollar (self, _terminal)
    Converts the tree leaf '$' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 151 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def dollar(self, _terminal):
         """
             Converts the tree leaf '$' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "$" )
dot()
def dot (self, _terminal)
    Converts the tree leaf '.' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 133 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def dot(self, _terminal):
         """
             Converts the tree leaf '.' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "." )
double_quote()
def double_quote (self, _terminal)
    Converts the tree leaf '"' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 139 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def double_quote(self, _terminal):
         """
             Converts the tree leaf '"' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "\"" )
epsilon()
def epsilon (self, _terminal)
    Converts the tree leaf epsilon '&' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 91 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def epsilon(self, _terminal):
         """
             Converts the tree leaf epsilon '&' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, '&' )
equals()
def equals (self, _terminal)
    Converts the tree leaf '=' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 205 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def equals(self, _terminal):
         """
             Converts the tree leaf '=' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "=" )
exclamation()
def exclamation (self, _terminal)
    Converts the tree leaf '!' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 169 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def exclamation(self, _terminal):
         """
             Converts the tree leaf '!' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "!" )
minus()
def minus (self, _terminal)
    Converts the tree leaf hyphen '-' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 103 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def minus(self, _terminal):
         """
             Converts the tree leaf hyphen '-' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "-" )
non_terminal()
def non_terminal (self, _non_terminals)
    Converts the tree leaf non terminal symbol into a NonTerminal ready to be used in the Chomsky Grammar.
Definition at line 85 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbols().
     def non_terminal(self, _non_terminals):
         """
             Converts the tree leaf non terminal symbol into a NonTerminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbols( _non_terminals, NonTerminal )
non_terminal_start()
def non_terminal_start (self, non_terminal)
    Converts the tree start symbol into a production ready to be used in the Chomsky Grammar.
Definition at line 70 of file tree_transformer.py.
     def non_terminal_start(self, non_terminal):
         """
             Converts the tree start symbol into a production ready to be used in the Chomsky Grammar.
         """
         log( 4, 'non_terminal: %s', non_terminal )
         new_production = Production()
         new_production.add( non_terminal[0] )
         return new_production
open_brace()
def open_brace (self, _terminal)
    Converts the tree leaf '{' symbol into a Terminal ready to be used in
    the Chomsky Grammar.
Definition at line 254 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def open_brace(self, _terminal):
         """
             Converts the tree leaf '{' symbol into a Terminal ready to be used in
             the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "{" )
open_bracket()
def open_bracket (self, _terminal)
    Converts the tree leaf '[' symbol into a Terminal ready to be used in
    the Chomsky Grammar.
Definition at line 241 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def open_bracket(self, _terminal):
         """
             Converts the tree leaf '[' symbol into a Terminal ready to be used in
             the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "[" )
open_paren()
def open_paren (self, _terminal)
    Converts the tree leaf '(' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 229 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def open_paren(self, _terminal):
         """
             Converts the tree leaf '(' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "(" )
percentage()
def percentage (self, _terminal)
    Converts the tree leaf '%' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 145 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def percentage(self, _terminal):
         """
             Converts the tree leaf '%' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "%" )
plus()
def plus (self, _terminal)
    Converts the tree leaf plus '+' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 109 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def plus(self, _terminal):
         """
             Converts the tree leaf plus '+' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "+" )
production()
def production (self, productions)
    Converts the tree leaf Terminal's and NonTerminal's symbols into a production ready to
    be used in the Chomsky Grammar.
Definition at line 286 of file tree_transformer.py.
     def production(self, productions):
         """
             Converts the tree leaf Terminal's and NonTerminal's symbols into a production ready to
             be used in the Chomsky Grammar.
         """
         log( 4, 'productions: %s', productions )
         new_production = Production()
         for production in productions:
             if isinstance( production, ( Terminal, NonTerminal ) ):
                 new_production.add( production )
         log( 4, "new_production: %s", new_production )
         return new_production
question()
def question (self, _terminal)
    Converts the tree leaf '?' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 199 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def question(self, _terminal):
         """
             Converts the tree leaf '?' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "?" )
quote()
def quote (self, _terminal)
    Converts the tree leaf single quote "'" symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 97 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def quote(self, _terminal):
         """
             Converts the tree leaf single quote "'" symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "'" )
semicolon()
def semicolon (self, _terminal)
    Converts the tree leaf ';' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 211 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def semicolon(self, _terminal):
         """
             Converts the tree leaf ';' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, ";" )
sharp()
def sharp (self, _terminal)
    Converts the tree leaf '#' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 163 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def sharp(self, _terminal):
         """
             Converts the tree leaf '#' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "#" )
slash()
def slash (self, _terminal)
    Converts the tree leaf '/' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 217 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def slash(self, _terminal):
         """
             Converts the tree leaf '/' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "/" )
star()
def star (self, _terminal)
    Converts the tree leaf '*' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 115 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def star(self, _terminal):
         """
             Converts the tree leaf '*' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "*" )
terminal()
def terminal (self, _terminals)
    Converts the tree leaf terminal into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 79 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbols().
     def terminal(self, _terminals):
         """
             Converts the tree leaf terminal into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbols( _terminals, Terminal )
tick()
def tick (self, _terminal)
    Converts the tree leaf '' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 181 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def tick(self, _terminal):
         """
             Converts the tree leaf '' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "" )
tilde()
def tilde (self, _terminal)
    Converts the tree leaf '~' symbol into a Terminal ready to be used in the Chomsky Grammar.
Definition at line 193 of file tree_transformer.py.
References ChomskyGrammarTreeTransformer._parse_symbol().
     def tilde(self, _terminal):
         """
             Converts the tree leaf '~' symbol into a Terminal ready to be used in the Chomsky Grammar.
         """
         return self._parse_symbol( _terminal, "~" )
The documentation for this class was generated from the following file:
tree_transformer.py