Trabalho 2 Formais: DynamicIterationDict Class Reference
DynamicIterationDict Class Reference
Public Member Functions
def __init__ (self, initial=None, is_set=False, emquote=False, index=False)
def __repr__ (self)
def __str__ (self)
def __contains__ (self, key)
def __len__ (self)
def __call__ (self, how_many_times=-1)
def __iter__ (self)
def __setitem__ (self, key, value)
def __getitem__ (self, key)
def __delitem__ (self, key)
def trim_indexes_sorted (self)
def trim_indexes_unsorted (self)
def keys (self, how_many_times=-1)
def values (self, how_many_times=-1)
def items (self, how_many_times=-1)
def get_key (self, index)
def get_value (self, index)
def get_key_value (self, index)
def get_iterator (self, target_generation, how_many_times=-1)
def not_iterate_over_new_items (self, how_many_times=1)
def fromkeys (self, iterable)
def append (self, element)
def remove (self, element)
def add (self, element)
def discard (self, element)
def copy (self)
def clear (self)
Public Attributes
keys_list
The list with the keys of this collection elements.
values_list
The list with the elements of this collection.
empty_slots
List the empty free spots for old items, used globally before the iteration starts.
filled_slots
List the empty free spots for old items, used globally after the iteration starts with new_items_skip_count
items_dictionary
A dictionary with the indexes of the elements in this collection.
new_items_skip_count
Whether the iteration process is allowed to use new items added on the current iteration.
new_items_skip_stack
A stack of new_items_skip_count which is required when the current iterator is called recursively.
maximum_iterable_index
Holds the global maximum iterable index used when new_items_skip_count is set.
Detailed Description
    A `dict()` like object which allows to dynamically add and remove items while iterating over
    its elements as in `for element in dynamic_set`
    https://wiki.python.org/moin/TimeComplexity
    https://stackoverflow.com/questions/4014621/a-python-class-that-acts-like-dict
Constructor & Destructor Documentation
__init__()
def __init__ (self, initial = None, is_set = False, emquote = False, index = False)
    Fully initializes and create a new dictionary.
    @param `initial` is a dictionary used to initialize it with new values.
Member Function Documentation
__call__()
def __call__ (self, how_many_times = -1)
    Return a iterable for the keys elements of this collection when calling its object as a
    function call.
    `how_many_times` is for how many iterations it should keep ignoring the new items.
__contains__()
def __contains__ (self, key)
    Determines whether this dictionary contains or not a given `key`.
__delitem__()
def __delitem__ (self, key)
    Given a `key` deletes if from this dict.
__getitem__()
def __getitem__ (self, key)
    Given a `key` returns its existent value.
__iter__()
def __iter__ (self)
    Called by Python automatically when iterating over this set and python wants to start
    the iteration process.
    Why have an __iter__ method in Python?
    https://stackoverflow.com/questions/36681312/why-have-an-iter-method-in-python
__len__()
def __len__ (self)
    Return the total length of this set.
__repr__()
def __repr__ (self)
    Return a full representation of all public attributes of this object set state for
    debugging purposes.
Referenced by LockableType.__setattr__().
__setitem__()
def __setitem__ (self, key, value)
    Given a `key` and `item` add it to this dictionary as a non yet iterated item, replacing
    the existent value. It a iteration is running, and the item was already iterated, then
    it will be updated on the `niterated_items` dict.
__str__()
def __str__ (self)
    Return a nice string representation of this collection.
Referenced by LockableType.__repr__().
add()
def add (self, element)
    Add a new element to the end of the list.
Referenced by DynamicIterationDict.__delitem__(), DynamicIterationDict.__setitem__(), Production.filter_non_terminals(), Production.replace(), and Production.trim_epsilons().
append()
def append (self, element)
    Add a new element to the end of the list.
Referenced by DynamicIterationDict.__setitem__(), and DynamicIterationDict.not_iterate_over_new_items().
clear()
def clear (self)
    Remove all items from this dict.
Referenced by DynamicIterationDict.trim_indexes_sorted().
copy()
def copy (self)
    Return a deep copy of this collection.
discard()
def discard (self, element)
    Remove new `element` anywhere in the container.
fromkeys()
def fromkeys (self, iterable)
    Initialize a dictionary with None default value, acting like a indexed set.
get_iterator()
def get_iterator (self, target_generation, how_many_times = -1)
    Get fully configured iterable given the getter `target_generation(index)` function.
    `how_many_times` is for how many iterations it should keep ignoring the new items.
Referenced by DynamicIterationDict.__call__(), DynamicIterationDict.__iter__(), DynamicIterationDict.items(), DynamicIterationDict.keys(), and DynamicIterationDict.values().
get_key()
def get_key (self, index)
    Given a `index` returns its corresponding key.
Referenced by DynamicIterationDict.__call__(), DynamicIterationDict.__iter__(), DynamicIterationDict.__str__(), and DynamicIterationDict.keys().
get_key_value()
def get_key_value (self, index)
    Given a `index` returns its corresponding (key, value) pair.
Referenced by DynamicIterationDict.items().
get_value()
def get_value (self, index)
    Given a `index` returns its corresponding value.
Referenced by DynamicIterationDict.values().
items()
def items (self, how_many_times = -1)
    Return a DynamicIterable over the (key, value) stored in this collection.
    `how_many_times` is for how many iterations it should keep ignoring the new items.
keys()
def keys (self, how_many_times = -1)
    Return a DynamicIterable over the keys stored in this collection.
    `how_many_times` is for how many iterations it should keep ignoring the new items.
Referenced by DynamicIterationDict.__str__().
not_iterate_over_new_items()
def not_iterate_over_new_items (self, how_many_times = 1)
    If called before start iterating over this dictionary, it will not iterate over the
    new keys added until the current iteration is over.
    `how_many_times` is for how many iterations it should keep ignoring the new items.
Referenced by DynamicIterationDict.get_iterator().
remove()
def remove (self, element)
    Remove new `element` anywhere in the container.
trim_indexes_sorted()
def trim_indexes_sorted (self)
    Fix the the outdated indexes on the internal lists after their dictionary removal,
    keeping the items original ordering O(n).
trim_indexes_unsorted()
def trim_indexes_unsorted (self)
    Fix the the outdated indexes on the internal lists after their dictionary removal.
    keeping the items original ordering O(k), where `k` is length of `self.empty_slots`.
values()
def values (self, how_many_times = -1)
    Return a DynamicIterable over the values stored in this collection.
    `how_many_times` is for how many iterations it should keep ignoring the new items.
The documentation for this class was generated from the following file:
dynamic_iteration.py