Trabalho 2 Formais: LockableType Class Reference
LockableType Class Reference
Public Member Functions
def __init__ (self)
def __setattr__ (self, name, value)
def __eq__ (self, other)
def __hash__ (self)
def __repr__ (self)
def __str__ (self)
def __len__ (self)
def lock (self)
def new (self, unlocked=True)
Public Attributes
locked
Controls whether the attributes changes of this object are allow or not.
str
Caches the string representation of this object, after locking its attributes changes with lock()
len
The cached length of this object, used while this object is in locked state.
Detailed Description
    An object type which can have its attributes changes locked/blocked after its `lock()`
    method being called.
    After locking, its string representation attribute is going to be saved as an attribute and
    returned when needed.
Constructor & Destructor Documentation
__init__()
def __init__ (self)
    How to handle call to __setattr__ from __init__?
    https://stackoverflow.com/questions/3870982/how-to-handle-call-to-setattr-from-init
Member Function Documentation
__eq__()
def __eq__ (self, other)
    Determines whether this object is equal to another one based on their hashes.
__hash__()
def __hash__ (self)
    Return the hash of this object based on its string representation.
__len__()
def __len__ (self)
    Python does not allow to dynamically/monkey patch its build in functions. Then, we create
    out own function and call it from the built-in function.
__repr__()
def __repr__ (self)
    Prints a representation of this object within all its attributes.
Referenced by LockableType.__setattr__().
__setattr__()
def __setattr__ (self, name, value)
    Block attributes from being changed after it is activated.
    https://stackoverflow.com/questions/17020115/how-to-use-setattr-correctly-avoiding-infinite-recursion
Referenced by LockableType.__init__().
__str__()
def __str__ (self)
    Python does not allow to dynamically/monkey patch its build in functions. Then, we create
    out own function and call it from the built-in function.
Referenced by LockableType.__repr__().
lock()
def lock (self)
    Block further changes to this object attributes and cache its length and string
    representation for faster access.
Referenced by Production.filter_non_terminals(), and Production.following_symbols().
new()
def new (self, unlocked = True)
    Creates and return a new copy of the current a object.
Referenced by Production.combinations(), Production.following_symbols(), Production.replace(), ChomskyGrammarSymbol.trim_epsilons(), and Production.trim_epsilons().
The documentation for this class was generated from the following file:
lockable_type.py